# Matrix and Systems of Linear Equation with Numpy

It is possible to do symbolic linear algebrea with [Sympy](http://www.sympy.org/en/index.html) but for numeric computations [Numpy](http://www.numpy.org/) is a high performance library that should be used.

Here is how it is described:

> NumPy is the fundamental package for scientific computing with Python. It contains among other things: [...]
 useful linear algebra, Fourier transform, and random number capabilities.

In this section we will see how to:

- Manipulate matrices;
- Solve Matrix equations;
- Calculate Matrix inverse and determinants.

## Review on Manipulating matrices

It is straightforward to create a Matrix using Numpy. Let us consider the following as a examples:

$$
A = \begin{pmatrix}
5 & 6 & 2\\
4 & 7 & 19\\
0 & 3 & 12
\end{pmatrix}
$$

$$
B = \begin{pmatrix}
14 & -2 & 12\\
4 & 4 & 5\\
5 & 5 & 1
\end{pmatrix}
$$


First, similarly to Sympy, we need to import Numpy:

In [20]:
import numpy as np

Now we can define $A$:

In [21]:
A = np.matrix([[5, 6, 2],
               [4, 7, 19],
               [0, 3, 12]])

In [22]:
A

matrix([[ 5,  6,  2],
        [ 4,  7, 19],
        [ 0,  3, 12]])

In [23]:
B = np.matrix([[14, -2, 12],
               [4, 4, 5],
               [5, 5, 1]])

In [24]:
B

matrix([[14, -2, 12],
        [ 4,  4,  5],
        [ 5,  5,  1]])

We can obtain the following straightforwardly:

- $5A$ (or any other scalar multiple of $A$);
- $A ^ 3$ (or any other exponent of $A$);
- $A + B$;
- $A - B$;
- $AB$

In [25]:
5 * A

matrix([[25, 30, 10],
        [20, 35, 95],
        [ 0, 15, 60]])

In [26]:
A ** 3

matrix([[ 557, 1284, 3356],
        [ 760, 2305, 6994],
        [ 288, 1074, 3519]])

In [27]:
A + B

matrix([[19,  4, 14],
        [ 8, 11, 24],
        [ 5,  8, 13]])

In [28]:
A - B

matrix([[ -9,   8, -10],
        [  0,   3,  14],
        [ -5,  -2,  11]])

In [29]:
A * B

matrix([[104,  24,  92],
        [179, 115, 102],
        [ 72,  72,  27]])

In [30]:
A@B

matrix([[104,  24,  92],
        [179, 115, 102],
        [ 72,  72,  27]])

## Solving Matrix equations

Solve system of homogenoeus linear equation

x + y - z = 0  
-2x - 3y + z = 0  
x - 4y + 2z = 0

We can use Numpy to (efficiently) solve large systems of equations of the form:

In [31]:
A = np.array([[ 1,  1, -1],
              [-2, -3, -1],
              [ 1, -4, 2]])

b = np.array([0, 0, 0])

solution = np.linalg.solve(A, b)
print("Solution:", solution)

Solution: [-0. -0. -0.]


Generally, the system of linear equation can be written into the form
$$Ax=b$$

Let us illustrate that with:

$$
A = \begin{pmatrix}
5 & 6 & 2\\
4 & 7 & 19\\
0 & 3 & 12
\end{pmatrix}
$$

$$
b = \begin{pmatrix}
-1\\
2\\
1
\end{pmatrix}
$$

In [32]:
A = np.matrix([[5, 6, 2],
               [4, 7, 19],
               [0, 3, 12]])
b = np.matrix([[-1], [2], [1]])

We use the `linalg.solve` command:

In [33]:
x = np.linalg.solve(A, b)
x

matrix([[ 0.45736434],
        [-0.62790698],
        [ 0.24031008]])

We can verify our result:

In [34]:
A * x

matrix([[-1.],
        [ 2.],
        [ 1.]])

---

**EXERCISE** Compute the solutions to the matrix equation $Bx=b$ (using the $B$ defined earlier).

---

## Matrix inversion and determinants

Computing the inverse of a matrix is straightforward:

In [35]:
Ainv = np.linalg.inv(A)
Ainv

matrix([[-0.20930233,  0.51162791, -0.7751938 ],
        [ 0.37209302, -0.46511628,  0.6744186 ],
        [-0.09302326,  0.11627907, -0.08527132]])

We can verify that $A^{-1}A=\mathbb{I}$:

In [36]:
A * Ainv

matrix([[ 1.00000000e+00,  4.99600361e-16, -2.77555756e-17],
        [ 1.38777878e-16,  1.00000000e+00,  1.80411242e-16],
        [ 1.11022302e-16,  1.11022302e-16,  1.00000000e+00]])

The above might not look like the identity matrix but if you look closer you see that the diagonals are all `1` and the off diagonals are a **very** small number (which from a computer's point of view is `0`).

In [38]:
import numpy as np
import sympy as sy

A = np.array(A, dtype=float)
Ainv = np.array(Ainv, dtype=float)

AA = sy.Matrix(A.tolist()) * sy.Matrix(Ainv.tolist())

To calculate the determinant:

In [ ]:
np.linalg.det(A)

-128.99999999999997

## Rank and Nullity

In [ ]:
A = np.array([[1, -1, 3],
              [5, -4, -4],
              [7, -6, 2]])

rank = np.linalg.matrix_rank(A)
nullity = A.shape[1] - rank

print("Rank of A:", rank)
print("Nullity of A:", nullity)

Rank of A: 2
Nullity of A: 1


In [ ]:
A = np.array([[1, 3, 4, 3],
              [3, 9, 12, 9],
              [1, 3, 4, 1]])

rank = np.linalg.matrix_rank(A)
nullity = A.shape[1] - rank

print("Rank of A:", rank)
print("Nullity of A:", nullity)

Rank of A: 2
Nullity of A: 2


In [28]:
# Exercise: Compute the inverse and determinant of B

# Compute the inverse of B
B_inv = np.linalg.inv(B)
print("Inverse of B:")
print(B_inv)

print("\n" + "="*50 + "\n")

# Compute the determinant of B
B_det = np.linalg.det(B)
print("Determinant of B:")
print(B_det)

print("\n" + "="*50 + "\n")

# Verify that B * B^(-1) = Identity matrix
np.allclose(B @ B_inv, np.eye(B.shape[0]))

Inverse of B:
[[ 6.25000000e-02 -1.84523810e-01  1.72619048e-01]
 [-6.25000000e-02  1.36904762e-01  6.54761905e-02]
 [-1.09511795e-17  2.38095238e-01 -1.90476190e-01]]


Determinant of B:
-336.0




True

---

**EXERCISE** Compute the inverse and determinant of $B$ (defined previously).

---
```
```


## Summary

In this section we have seen how to using Numpy:

- Manipulate matrices;
- Solve linear systems;
- Compute Matrix inverses and determinants.

This again just touches on the capabilities of Numpy.

Let us take a look at [Pandas](03 - Data analysis with Pandas.ipynb) for data analysis.